version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-tools
    tty: true
    image: "<%= image %>"
    container_name: "<%= containerName %>"
    ports: <% ports.forEach(port => { %>
      - "<%= port %>:<%= port %>"<%}) %>
    volumes:
      - .:/app
      <%if(images.length > 0){ %>
    links: <% images.forEach(image => { %>
      -  <%= image %><%})} %>
    environment:
      NODE_ENV: "development"<% envs.forEach(env => { for(key in env){ %>
      <%= key %>: <%= env[key] %><%}});%> <% images.forEach(image => {%>
  <%=image%>:
    image: <%=image%>
  <%});%>
