version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "<%= image %>"
    container_name: "<%= containerName %>"
    ports: <% ports.forEach(port => { %>
      - "<%= port %>:<%= port %>"<% }); if(images.length > 0){ %>
    links: <% images.forEach(image => { %>
      - <%= image %><% });} %>
    environment: <% envs.forEach(env => { for(key in env){ %>
      <%= key %>: <%= env[key] %><%}});%> <% images.forEach(image => {%>
  <%=image%>:
    image: <%=image%>
  <%});%>
